
#ARTISTS

gabby = Artist.create(name: "Gabby Lopez", bio: "Gabrielle Lopez was born in Kingston, Jamaica.  At a very young age, she moved to Rhode Island to live with her mother’s family. Lopez currently attends Rhode Island College working on her BFA in Metalsmithing and Jewelry Design.  Her work explores the concept of energy release through motion and physical interaction with her pieces.", image_main: "http://www.gabriellelopezmetals.com/uploads/2/5/6/7/25677216/1335125_orig.jpg", image_thumb: "http://www.gabriellelopezmetals.com/uploads/2/5/6/7/25677216/1390099894.png", contact_email: "gabriellezalopez@gmail.com" )

rory = Artist.create(name: "Rory Dlugos", bio: "In fragmenting the human figure, I hope to express loss of control, or the inability to know one’s future. On a daily basis, I am bombarded with this anxiety-ridden dilemma. In my work, this struggle manifests itself in the figures’ expressions and poses. The seamless integration of figures into the background can be seen as their successful ability to merge with their changing environment; in other words, a positive adaptation of self. I feel it is more important to focus on questions and to wrestle with them. This is analogous to the process of making a painting; I want my work to contain a spirit of questioning as well as the struggle to find answers.", image_main: "https://lh5.googleusercontent.com/3cJzySs6G2TtFgIsWQWQ8zlDP_igGaHbm6ZFfprW5lF3sP0eSVZXT1sE2ojvHQrGQW7tHA=w1120-h752", image_thumb: "http://m.c.lnkd.licdn.com/mpr/pub/image-1DO7sqVdaGYQIGHO5I5hUW5IQKxslJTux-5Cnh4WQi1ncs_Z1DOC2TbdQ9Cmz6TE9fKU/rory-dlugos.jpg", contact_email: "rdlugos@friars.providence.edu")

kyle = Artist.create(name: "Kyle Turner", bio: "A God amongst men. And oh yeah, he paints. Ladies, he's taken", image_main: "http://ppcdn.500px.org/26259019/9cbd06330fa66f7d6f616288a4c8068cf30ab8ba/5.jpg", image_thumb: "https://lh5.googleusercontent.com/-5D5jw19WKmA/TEaQKG9JqcI/AAAAAAAAABI/0tSJ5Q6y4aA/w549-h679-no/_MG_00322.jpg", contact_email: "")

grace = Artist.create(name: "Grace Mccurn", bio: "Amazing, amazing. Amazing", image_main = "http://ppcdn.500px.org/26434181/c8ae0fd26cc8bc05a2377eff8e6404ebf2738961/5.jpg", image_thumb: "http://pacdn.500px.org/2672663/51186ff83f48ab4f46e361190ece911714b32312/1.jpg?3", contact_email: "gracemccurn@gmail.com")

katryn = Artist.create(name: "Katryn Mcintosh", bio: "Katryn McIntosh is an artist & full stack web developer living in Providence, RI. She develops systems, in both her artwork and her career, that integrate disparate parts to produce a faceted yet cohesive whole. Technology and textiles remain her preferred mediums, but her body of work is more readily defined by a consistent approach than a particular product. Katryn received her BFA in painting from the Rhode Island School of Design in 2007. While at RISD, she participated in the European Honors program – a year of independent study in Rome, Italy. Before focusing on technology, Katryn pursued a brief career in the fashion industry that enriched her sense of color and streamlined her approach to production and business. She is also particularly passionate about working with organizations that encourage young women who have an interest in leadership or the STEM fields. In early April 2014, she volunteered for New England Give Camp. In collaboration with three other technology professionals, she built a new Web site for Girls, Inc of Greater Lowell over the course of a weekend. She continues to work with them on the re-design of their Web site and communication materials. Outside of the studio, her loves include reading, Minecraft, and spending time with her dog Cowboy / her sugar gliders Flower and Coyote.", image_main: "https://lh3.googleusercontent.com/dEwQsqnogH3Md6avzJrm6c9IiA68ABMXLvvT6PWDLGTxo6ZeOUQF75pOfEK4CZlqgPTfWg=w1249-h605", image_thumb: "https://drive.google.com/a/fordham.edu/folderview?id=0BxC27v75x8a3OC16RU1DNVNTczQ&usp=sharing", contact_email: "katryn.mcintosh@gmail.com" )

phil = Artist.create(name: "Phil Elverum", bio: "I was born in 1978. I come from the town of Anacortes, Washington. Since 1997 my primary life’s work has been making studio-based music, first under the name “the Microphones” (1997 – 2002) and then “Mount Eerie” (2003 – present). In addition to this I have played in other bands (D+, Old Time Relijun), produced other peoples’ recordings and dabbled in painting, writing, and photography.", image_main: "http://www.pwelverumandsun.com/images/switzerland.jpg", image_thumb: "http://www.pwelverumandsun.com/images/mounteerie/mounteerie_byMarcKrause.jpg", contact_email: "pw@pwelverumandsun.com" )


richie = Artist.create(name: "Richie Stewart", bio: "The following is a real conversation: Me: Hey Richie. It’d be great if you could send me some background info. about yourself so I can include a bio in the materials for your event. Richie: Sure. How about this?: “Designer / Letterer / Detail Obsesser / Founder of Commoner, Inc.” Me: Can you send me a bit more? People will want to know more about you. Ya know - they need a reason to get up at 8:30 in the morning. How about some more background, as well as a list of your clients?“ Richie: …Okay, how about this? \"The world is fucking ugly. It’s up to all of us to find the beauty that’s been buried underneath all the bullshit and share it with other people. That’s how I pay my rent.\” Me: I’ll just write it myself. So come listen to Richie Stewart - designer, letterer, detail obsesser, and found of Commoner, Inc. - share his own story of how he went from perpetual school-skipper to “working class” designer, having worked with clients such as Nike, CNN, Miller Lite, Market Basket, Sebago, Johnny Cupcakes, Salvation Army, Atlas Ventures, and the Hunger Games movie.", image_main: "https://d13yacurqjgara.cloudfront.net/users/22225/screenshots/1031550/attachments/124548/B.jpg", image_thumb: "https://pbs.twimg.com/profile_images/475726157581533184/kClHLuGA.jpeg", contact_email: "" )
